name: DraxTube Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Launcher
        run: |
          # Non usiamo ps2sdk-ports-install per ora
          make
          
      - name: Save ELF
        uses: actions/upload-artifact@v4
        with:
          name: NeutrinoLauncher-DraxTube
          path: NeutrinoLauncher.elf
