name: DraxTube Build System

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container: ps2dev/ps2dev:latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Tools
        run: |
          # Installiamo make e gli strumenti necessari
          apk add --no-cache make build-base git

      - name: Compile DraxTube Launcher
        run: |
          # Usiamo il percorso completo per i tool della PS2
          export PATH=$PATH:$PS2DEV/bin:$PS2DEV/ee/bin:$PS2DEV/iop/bin
          make
          
      - name: Upload ELF
        uses: actions/upload-artifact@v4
        with:
          name: DraxTube-Launcher
          path: NeutrinoLauncher.elf
